const materialsToUnify = [
    'steel',
    'refined_obsidian',
    'utherium',
    'obsidian',
    'coke',
    'terrasteel',
    'regalium',
    'silver',
    'potassium_nitrate',
    'fluix_steel',
    'coal',
    'dimensionalshard',
    'emerald',
    'ender_pearl',
    'resonating',
    'lumium',
    'silicon',
    'iron',
    'bronze',
    'refined_glowstone',
    'cinnabar',
    'fluix',
    'nebu',
    'charcoal',
    'knightslime',
    'nether_brick',
    'scorched_brick',
    'lead',
    'cobalt',
    'ruby',
    'slimesteel',
    'dragonstone',
    'mana',
    'brick',
    'wood',
    'end_stone',
    'hepatizon',
    'brass',
    'enderium',
    'silicon_bronze',
    'peridot',
    'froststeel',
    'charged_certus_quartz',
    'thallasium',
    'apatite',
    'niter',
    'electrum',
    'manyullyn',
    'seared_brick',
    'iridium',
    'fluix_iron',
    'diamond',
    'quartz',
    'manasteel',
    'constantan',
    'gold',
    'soulsteel',
    'netherite',
    'otherworld_ashes',
    'zinc',
    'iesnium',
    'bitumen',
    'mana_diamond',
    'sulfur',
    'sapphire',
    'glowstone',
    'tin',
    'dimensional',
    'nickel',
    'draconium',
    'aluminum',
    'elementium',
    'queens_slime',
    'osmium',
    'ender',
    'draconium_awakened',
    'lapis',
    'signalum',
    'arcane',
    'graphite',
    'spirit_attuned',
    'salt',
    'redstone',
    'carbonic_fluix',
    'lithium',
    'certus_quartz',
    'invar',
    'fluorite',
    'burnt_otherstone',
    'uranium',
    'cloggrum',
    'copper',
    'prismarine',
    'rose_gold',
    'pig_iron',
    'cast_iron'
]
// Used to determine which material types to unify
const typesToUnify = ['nugget', 'ingot', 'gem', 'storage_block', 'ore', 'dust', 'gear', 'plate', 'rod'];

// Used for creating tags on custom ore processing materials
const metals = [
    'aluminum',
    'cloggrum',
    'cobalt',
    'copper',
    'froststeel',
    'gold',
    'iesnium',
    'iron',
    'lead',
    'nebu',
    'nickel',
    'osmium',
    'regalium',
    'silver',
    'thallasium',
    'tin',
    'uranium',
    'utherium',
    'zinc'
];

const meltingPoints = {
    utherium: { temp: 1070 },
    thallasium: { temp: 800 },
    signalum: { temp: 1272 },
    regalium: { temp: 620 },
    nebu: { temp: 1400 },
    lumium: { temp: 1354 },
    iesnium: { temp: 850 },
    froststeel: { temp: 860 },
    enderium: { temp: 1450 },
    cloggrum: { temp: 650 },
    sulfur: { temp: 115 },
    redstone: { temp: 660 },
    potassium_nitrate: { temp: 334 },
    lapis: { temp: 115 },
    fluorite: { temp: 1418 },
    dimensional: { temp: 1450 },
    coal: { temp: 1149 },
    cinnabar: { temp: 580 },
    bitumen: { temp: 115 },
    apatite: { temp: 450 },
    aeternium: { temp: 1250 },
    alfsteel: { temp: 1450 },
    elementium: { temp: 875 },
    gaia_spirit: { temp: 1350 },
    infused_iron: { temp: 850 },
    manasteel: { temp: 900 },
    terminite: { temp: 840 },
    terrasteel: { temp: 975 },
    energized_steel: { temp: 875 },
    blazing: { temp: 950 },
    niotic: { temp: 1250 },
    spirited: { temp: 1350 },
    nitro: { temp: 1450 }
};