BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("starcraft:kivi_stone_recipe")
    .pattern("aaa", "aaa", "aaa")
    .pattern("aaa", "aba", "aaa")
    .pattern("aaa", "aca", "aaa")
    .center("c", 'minecraft:coal_block')
    .where("a", 'ae2:smooth_sky_stone_block')
    .where("b", 'minecraft:crying_obsidian')
    .craftingItem('enderio:grains_of_infinity')
    .resultItem('2x xycraft_world:kivi')
    .build());

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("starcraft:mysterious_cube_recipe")
    .pattern("aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa")
    .pattern("aaaaa", "acdca", "aggga", "acdca", "aaaaa")
    .pattern("aaaaa", "adeda", "aggga", "adeda", "aaaaa")
    .pattern("aaaaa", "acdca", "aggga", "acdca", "aaaaa")
    .pattern("aaaaa", "abbba", "abfba", "abbba", "aaaaa")
    .center("f", 'minecraft:diamond_block')
    .where("a", 'xycraft_world:kivi')
    .where("b", 'ae2:fluix_block')
    .where("c", 'minecraft:redstone_block')
    .where("d", 'minecraft:lapis_block')
    .where("e", 'minecraft:iron_block')
    .where("g", 'ae2:quartz_block')
    .craftingItem('evilcraft:environmental_accumulation_core')
    .resultItem('ae2:mysterious_cube')
    .build());
