// priority: 1

const itemToBan = [
    'torcherino:torcherino',
    'torcherino:compressed_torcherino',
    'torcherino:double_compressed_torcherino',
    'ars_nouveau:glyph_phantom_block',
    'ars_nouveau:glyph_place_block',
    'ars_nouveau:glyph_wall',
    'ars_nouveau:glyph_intangible',
    'industrialforegoing:enchantment_applicator',
    'ae2:matter_cannon',
    'mekanism:cardboard_box',
    'botania:terraform_rod',
    'botania:laputa_shard',
    'tconstruct:efln_ball',
    'ae2:interface',
    'ae2:crafting_unit',
    'ae2:pattern_provider',
    'evilcraft:lightning_bomb',
    'ifeu:weather_controller',
    'avaritia:infinity_shovel',
    'mekanism:creative_fluid_tank',
    'avaritia:infinity_chest',
    'forestry:mailbox',
    'forestry:trade_station',
    'avaritia:endest_pearl',
    'industrialforegoing:infinity_drill',
    'industrialforegoing:infinity_nuke',
    'composite:material_creative_reinforced_book',
    'ars:nouveau_glyph_intangible',
    'mekanism:upgrade_anchor',
    'mekanism:robit',
    'mekanism:dimensional_stabilizer',
    'ars:nouveau_glyph_phantom_block',
    'ars:nouveau_glyph_place_block',
    'ars:nouveau_glyph_wall',
    'ifeu:blueprint',
    'industrialforegoing:material_stonework_factory',
    'mekanism:creative_bin',
    'ifeu:rule_controller',
    'ifeu:time_controller',
    'chunkloaders:basic_chunk_loader',
    'extendedae:plus_infinity_biginteger_cell',
    'chunkloaders:advanced_chunk_loader',
    'buildcraftrobotics:requester',
    'buildcraftlib:guide',
    'buildcraftbuilders:builder',
    'buildcraftbuilders:architect',
    'buildcraftbuilders:library',
    'buildcraftbuilders:replacer',
    'buildcraftbuilders:quarry',
    'buildcraftfactory:mining_well',
    'chunkloaders:ultimate_chunk_loader',
    'functionalstorage:creative_vending_upgrade',
    'buildcraftrobotics:zone_planner',
    'buildcraftbuilders:filler',
    'buildcraftfactory:flood_gate',
    'avaritia:infinity_umbrella',
    'cataclysm:laser_gatling',
    'extendedae:plus_entity_speed_ticker',
    'draconicevolution:disenchanter',
    'botania:floating_rannuncarpus_chibi',
    'botania:floating_rannuncarpus',
    'botania:rannuncarpus_chibi',
    'botania:rannuncarpus',
    'tconstruct:shuriken',
    'composite:material_duplichanted_book',
    'avaritia:infinity_clock',
    'ars:nouveau_glyph_break',
    'ae2:io_port',
    'expatternprovider:ex_io_port'
]

const idToRemove = [
    'goety:haunted/haunted_jug',
    'mushroom_concept:alloy/steel',
    'ae2:inscriber/engineering_processor',
    'ae2:inscriber/logic_processor',
    'ae2:inscriber/calculation_processor',
    'mekanism:processing/uranium/uranium_oxide',
    'mekanism:crystallizing/salt',
    'mekanism:processing/uranium/sulfuric_acid',
    'mekanism:oxidizing/sulfur_dioxide',
    'botania:mana_infusion/manasteel_block',
    'botania:mana_infusion/manasteel',
    'botania:alfheim_portal',
    'ae2:decorative/quartz_glass',
    'advanced_ae:quantum_processor',
    'forestry:sturdy_machine',
    'industrialforegoing:ore_laser_base',
    'industrialforegoing:laser_drill',
    'avaritia:extreme_crafting_table',
    'draconicevolution:components/draconium_ingot_from_ore',
    'draconicevolution:components/draconium_ingot_from_dust',
    'enderio:smelting/draconicevolution/components/draconium_ingot_from_dust',
    'enderio:smelting/draconicevolution/components/draconium_ingot_from_ore',
    'draconicevolution:components/draconium_core',
    'draconicevolution:components/wyvern_core',
    'botania:pure_daisy/livingwood',
    'botania:pure_daisy/livingrock',
    'sgjourney:classic_stargate_ring_block',
    'sgjourney:classic_stargate_base_block',
    'sgjourney:classic_stargate_chevron_block'
]

const itemToRemove = [
    // 'ars_nouveau:imbuement_chamber',
    // 'ars_nouveau:source_jar',
    // 'ars_nouveau:relay',
    // 'ars_nouveau:sourcestone',
    // 'ars_nouveau:arcane_core',
    '#botanypots:basic_botany_pots',
    'evilcraft:eternal_water',
    'cagedmobs:mob_cage',
    'cagedmobs:hopping_mob_cage',
    'cagedmobs:speed_ii_upgrade',
    'cagedmobs:speed_iii_upgrade',
    'cagedmobs:looting_upgrade',
    'mekanism:metallurgic_infuser',
    'beyonddimensions:net_creater',
    'ae2:energy_acceptor',
    'ae2:controller',
    'beyonddimensions:dimensional_connect_block',
    'beyonddimensions:net_furnace_block',
    'beyonddimensions:net_pump_block',
    'beyonddimensions:net_hopper_block',
    'ae2:drive',
    'beyonddimensions:net_control',
    'beyonddimensions:net_interface',
    'beyonddimensions:net_pathway',
    'ae2:cell_component_1k',
    'ae2:cell_component_4k',
    'ae2:cell_component_16k',
    'ae2:cell_component_64k',
    'beyonddimensions:mana_pool_pathway',
    'beyonddimensions:ars_source_pathway',
    'botania:livingwood_log',
    'botania:livingrock',
    'botania:rune_water',
    'botania:rune_fire',
    'botania:rune_earth',
    'botania:rune_air',
    'botania:rune_mana',
    'botania:rune_spring',
    'botania:rune_summer',
    'botania:rune_autumn',
    'botania:rune_winter',
    'botania:rune_pride',
    'botania:rune_wrath',
    'botania:rune_gluttony',
    'botania:rune_envy',
    'botania:rune_sloth',
    'botania:rune_greed',
    'botania:rune_lust',
    'occultism:storage_stabilizer_tier1',
    'occultism:storage_stabilizer_tier2',
    'occultism:storage_stabilizer_tier3',
    'occultism:storage_stabilizer_tier4',
    'occultism:spirit_attuned_gem',
    'occultism:otherstone',
    'ae2:quantum_link',
    'ae2:import_bus',
    'ae2:export_bus',
    'ae2:storage_bus',
    'ae2:molecular_assembler',
    'fluxnetworks:flux_core',
    'advanced_ae:reaction_chamber',
    'chicken_roost:brown_egg',
    'chicken_roost:green_egg',
    'chicken_roost:blue_egg',
    'chicken_roost:magenta_egg',
    'chicken_roost:light_blue_egg',
    'chicken_roost:cyan_egg',
    'chicken_roost:yellow_egg',
    'chicken_roost:orange_egg',
    'chicken_roost:lime_egg',
    'chicken_roost:white_egg',
    'chicken_roost:purple_egg',
    'chicken_roost:light_gray_egg',
    'chicken_roost:pink_egg',
    'chicken_roost:black_egg',
    'chicken_roost:red_egg',
    'chicken_roost:gray_egg',
    '#chicken_roost:blocks/all',
    'expatternprovider:wireless_tool',
    'expatternprovider:wireless_connect',
    'ae2:vibration_chamber',
    'industrialforegoing:machine_frame_pity',
    'chicken_roost:roost',
    'chicken_roost:soul_extractor',
    'chicken_roost:breeder',
    'chicken_roost:trainer',
    'chicken_roost:chicken_food_tier_1',
    'chicken_roost:chicken_food_tier_2',
    'chicken_roost:chicken_food_tier_3',
    'chicken_roost:chicken_food_tier_4',
    'chicken_roost:chicken_food_tier_5',
    'chicken_roost:chicken_food_tier_6',
    'chicken_roost:chicken_food_tier_7',
    'chicken_roost:chicken_food_tier_8',
    'chicken_roost:chicken_food_tier_9',
    '#chicken_roost:blocks/all',
    'chicken_roost:chickenstorage',
    'ae2:blank_pattern',
    'enderio:primitive_alloy_smelter',
    'immersiveengineering:cokebrick',
    'modularrouters:modular_router',
    'mekanism:creative_fluid_tank',
    'mekanism:creative_bin',
    'mekanism:creative_energy_cube',
    'mekanism:creative_chemical_tank',
    'draconicevolution:creative_op_capacitor',
    'enderio:creative_power',
    'draconicevolution:creative_capacitor',
    'immersiveengineering:blastbrick',
    'mekanism:steel_casing',
    'cookingforblockheads:sink',
    'chunkloaders:single_chunk_loader',
    'chunkloaders:basic_chunk_loader',
    'chunkloaders:advanced_chunk_loader',
    'chunkloaders:ultimate_chunk_loader'
    
    


    

    // 'create:cogwheel',
    // 'create:large_cogwheel',
    // 'cagedmobs:mob_cage',
    // 'cagedmobs:hopping_mob_cage',
    // 'beyonddimensions:net_creater',

    // 'create:sweet_roll',
    // 'botania:runic_altar',
    // 'modularrouters:modular_router',
    // 'mekanism:steel_casing',
    // 'cookingforblockheads:sink',
    // 'evilcraft:eternal_water',
    // 'thermal:device_rock_gen',
    // 'pipez:fluid_pipe',
    // 'pipez:item_pipe',
    // 'mekanism:basic_mechanical_pipe',
    // 'mekanism:basic_logistical_transporter',
    // 'mekanism:basic_universal_cable',
    // 'mekanism:basic_pressurized_tube',
    // 'thermal:machine_frame',
    // Item.of('expatternprovider:infinity_cell', '{record:{"#c":"ae2:f",id:"minecraft:water"}}'),
    // Item.of('expatternprovider:infinity_cell', '{record:{"#c":"ae2:i",id:"minecraft:cobblestone"}}'),
    // 'naturesaura:chunk_loader',

]


ServerEvents.recipes(event => {
    console.log("Remove items is running")

    for (let toRemove of itemToRemove) {
        event.remove({ output: toRemove })
    }
    for (let toIdRemove of idToRemove) {
        event.remove({ id: toIdRemove })
    }
    for (let toBan of itemToBan) {
        event.remove({ output: toBan })
    }

    console.log("Remove items is done")
})
