#How should the chunks be animated?\n 0: Chunks always appear from below\n 1: Chunks always appear from above\n 2: Chunks appear from below if they are lower than the Horizon and from above if they are higher than the Horizon\n 3: Chunks \"slide in\" from their respective cardinal direction (Relative to the Player)\n 4: Same as 3 but the cardinal direction of a chunk is determined slightly different (Just try both :D)
#Range: 0 ~ 4
mode = 0
#The function that should be used to control the movement of chunks in ALL animation modes\nIf you want a visual comparison there is a link on the curseforge page\n0: Linear, 1: Quadratic, 2: Cubic, 3: Quartic, 4: Quintic, 5: Expo, 6: Sin, 7: Circle, 8: Back, 9: Bounce, 10: Elastic
#Range: 0 ~ 10
easingFunction = 6
#How long should the animation last? (In milliseconds)
#Range: > 0
animationDuration = 1000
#If enabled chunks that are next to the player will not animate
disableAroundPlayer = false

